package espoch.edu.ec.pampara;

public class RegistroParticipantes extends javax.swing.JFrame {

    /**
     * Creates new form RegistroParticipantes
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngServicios = new javax.swing.ButtonGroup();
        btngTurno = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        lblServicios = new javax.swing.JLabel();
        ckxAlmuerzo = new javax.swing.JCheckBox();
        ckxTransporte = new javax.swing.JCheckBox();
        ckxMaterialApoyo = new javax.swing.JCheckBox();
        lblTurno = new javax.swing.JLabel();
        rbnManana = new javax.swing.JRadioButton();
        rbnTarde = new javax.swing.JRadioButton();
        btnRegistro = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        lblMostrarResultados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("REGISTRO DE PARTICIPANTES");

        lblNombre.setText("NOMBRE DEL PARTICIPANTE:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblCategoria.setText("CATEGORIA DE PARTICIPACION:");

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTUDIANTE", "PROFESIONAL", "INVITADO ESPECIAL" }));
        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });

        lblServicios.setText("SERVICIOS REQUERIDOS:");

        btngServicios.add(ckxAlmuerzo);
        ckxAlmuerzo.setText("ALMUERZO");
        ckxAlmuerzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckxAlmuerzoActionPerformed(evt);
            }
        });

        btngServicios.add(ckxTransporte);
        ckxTransporte.setText("TRANSPORTE");

        btngServicios.add(ckxMaterialApoyo);
        ckxMaterialApoyo.setText("MATERIAL DE APOYO");
        ckxMaterialApoyo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckxMaterialApoyoActionPerformed(evt);
            }
        });

        lblTurno.setText("TURNO DE ASISTENCIA");

        btngTurno.add(rbnManana);
        rbnManana.setText("MAÑANA");

        btngTurno.add(rbnTarde);
        rbnTarde.setText("TARDE");

        btnRegistro.setText("REGISTRAR PARTICIPANTES");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnMostrar.setText("MOSTRAR REGISTRO");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        lblMostrarResultados.setText("___________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoria)
                            .addComponent(lblNombre)
                            .addComponent(lblServicios)
                            .addComponent(lblTurno))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckxAlmuerzo)
                                    .addComponent(rbnManana))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbnTarde)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ckxTransporte)
                                        .addGap(31, 31, 31)
                                        .addComponent(ckxMaterialApoyo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMostrarResultados)
                                .addGap(177, 177, 177))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServicios)
                    .addComponent(ckxAlmuerzo)
                    .addComponent(ckxTransporte)
                    .addComponent(ckxMaterialApoyo))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTurno)
                    .addComponent(rbnManana)
                    .addComponent(rbnTarde))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(lblMostrarResultados)
                .addGap(135, 135, 135))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:

        // Layout code omitted for brevity - use your existing layout code here        
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText();
        String categoria = (String)cbxCategoria.getSelectedItem();
        String almuerzo = Boolean.toString(ckxAlmuerzo.isSelected());
        String transporte = Boolean.toString(ckxTransporte.isSelected());
        String material = Boolean.toString(ckxMaterialApoyo.isSelected());
        boolean turnoManana = rbnManana.isSelected();
        boolean turnoTarde = rbnTarde.isSelected();
        String turno="";
        
        if(turnoManana){
            turno="mañana";
        }else if(turnoTarde){
            turno="tarde";
        }
        
        String[] datosUsuario = new String[6];
        datosUsuario[0]=nombre;
        datosUsuario[1]=categoria;
        datosUsuario[2]=almuerzo;
        datosUsuario[3]=transporte;
        datosUsuario[4]=material;
        datosUsuario[5]=turno;
        
        for (int i = 0; i < 6; i++) {
            System.out.println("Datos: " +datosUsuario[i]);
            
        }

    }//GEN-LAST:event_btnRegistroActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void ckxMaterialApoyoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckxMaterialApoyoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ckxMaterialApoyoActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMostrarActionPerformed

    private void ckxAlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckxAlmuerzoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckxAlmuerzoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.ButtonGroup btngServicios;
    private javax.swing.ButtonGroup btngTurno;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JCheckBox ckxAlmuerzo;
    private javax.swing.JCheckBox ckxMaterialApoyo;
    private javax.swing.JCheckBox ckxTransporte;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblMostrarResultados;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblServicios;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JRadioButton rbnManana;
    private javax.swing.JRadioButton rbnTarde;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
